
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	private global::Gtk.Table table3;
	private global::Gtk.ComboBox comboboxDatatype;
	private global::Gtk.ComboBox comboboxTextComp;
	private global::Gtk.Entry entryColumnEnd;
	private global::Gtk.Entry entryColumnStart;
	private global::Gtk.Entry entryComparisonValue;
	private global::Gtk.Entry entryRowEnd;
	private global::Gtk.Entry entryRowStart;
	private global::Gtk.Label labelColEnd;
	private global::Gtk.Label labelColStart;
	private global::Gtk.Label labelComparisonValue;
	private global::Gtk.Label labelDatatype;
	private global::Gtk.Label labelRowEnd;
	private global::Gtk.Label labelRowStart;
	private global::Gtk.Label labelTextComp;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.Table table4;
	private global::Gtk.RadioButton radioAddition;
	private global::Gtk.RadioButton radioDivision;
	private global::Gtk.RadioButton radioMultiplication;
	private global::Gtk.RadioButton radioSubtraction;
	private global::Gtk.Label frameOperations;
	private global::Gtk.HButtonBox hbuttonbox2;
	private global::Gtk.Button buttonOk;
	private global::Gtk.Button buttonCancel;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table (((uint)(4)), ((uint)(4)), true);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.comboboxDatatype = global::Gtk.ComboBox.NewText ();
		this.comboboxDatatype.Name = "comboboxDatatype";
		this.table3.Add (this.comboboxDatatype);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3 [this.comboboxDatatype]));
		w1.TopAttach = ((uint)(3));
		w1.BottomAttach = ((uint)(4));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.comboboxTextComp = global::Gtk.ComboBox.NewText ();
		this.comboboxTextComp.Name = "comboboxTextComp";
		this.table3.Add (this.comboboxTextComp);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.comboboxTextComp]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.LeftAttach = ((uint)(3));
		w2.RightAttach = ((uint)(4));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.entryColumnEnd = new global::Gtk.Entry ();
		this.entryColumnEnd.CanFocus = true;
		this.entryColumnEnd.Name = "entryColumnEnd";
		this.entryColumnEnd.IsEditable = true;
		this.entryColumnEnd.InvisibleChar = '●';
		this.table3.Add (this.entryColumnEnd);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryColumnEnd]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(3));
		w3.RightAttach = ((uint)(4));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.entryColumnStart = new global::Gtk.Entry ();
		this.entryColumnStart.CanFocus = true;
		this.entryColumnStart.Name = "entryColumnStart";
		this.entryColumnStart.IsEditable = true;
		this.entryColumnStart.InvisibleChar = '●';
		this.table3.Add (this.entryColumnStart);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryColumnStart]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.entryComparisonValue = new global::Gtk.Entry ();
		this.entryComparisonValue.CanFocus = true;
		this.entryComparisonValue.Name = "entryComparisonValue";
		this.entryComparisonValue.IsEditable = true;
		this.entryComparisonValue.InvisibleChar = '●';
		this.table3.Add (this.entryComparisonValue);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryComparisonValue]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.entryRowEnd = new global::Gtk.Entry ();
		this.entryRowEnd.CanFocus = true;
		this.entryRowEnd.Name = "entryRowEnd";
		this.entryRowEnd.IsEditable = true;
		this.entryRowEnd.InvisibleChar = '●';
		this.table3.Add (this.entryRowEnd);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryRowEnd]));
		w6.LeftAttach = ((uint)(3));
		w6.RightAttach = ((uint)(4));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.entryRowStart = new global::Gtk.Entry ();
		this.entryRowStart.CanFocus = true;
		this.entryRowStart.Name = "entryRowStart";
		this.entryRowStart.IsEditable = true;
		this.entryRowStart.InvisibleChar = '●';
		this.table3.Add (this.entryRowStart);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryRowStart]));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.labelColEnd = new global::Gtk.Label ();
		this.labelColEnd.Name = "labelColEnd";
		this.labelColEnd.LabelProp = global::Mono.Unix.Catalog.GetString ("Spalte (End):");
		this.table3.Add (this.labelColEnd);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelColEnd]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.labelColStart = new global::Gtk.Label ();
		this.labelColStart.Name = "labelColStart";
		this.labelColStart.LabelProp = global::Mono.Unix.Catalog.GetString ("Spalte (Start):");
		this.table3.Add (this.labelColStart);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelColStart]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.labelComparisonValue = new global::Gtk.Label ();
		this.labelComparisonValue.Name = "labelComparisonValue";
		this.labelComparisonValue.LabelProp = global::Mono.Unix.Catalog.GetString ("Vergleichswert:");
		this.table3.Add (this.labelComparisonValue);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelComparisonValue]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.labelDatatype = new global::Gtk.Label ();
		this.labelDatatype.Name = "labelDatatype";
		this.labelDatatype.LabelProp = global::Mono.Unix.Catalog.GetString ("Datentyp:");
		this.table3.Add (this.labelDatatype);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelDatatype]));
		w11.TopAttach = ((uint)(3));
		w11.BottomAttach = ((uint)(4));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.labelRowEnd = new global::Gtk.Label ();
		this.labelRowEnd.Name = "labelRowEnd";
		this.labelRowEnd.LabelProp = global::Mono.Unix.Catalog.GetString ("Zeile (Ende):");
		this.table3.Add (this.labelRowEnd);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelRowEnd]));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.labelRowStart = new global::Gtk.Label ();
		this.labelRowStart.Name = "labelRowStart";
		this.labelRowStart.LabelProp = global::Mono.Unix.Catalog.GetString ("Zeile (Start):");
		this.table3.Add (this.labelRowStart);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelRowStart]));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.labelTextComp = new global::Gtk.Label ();
		this.labelTextComp.Name = "labelTextComp";
		this.labelTextComp.LabelProp = global::Mono.Unix.Catalog.GetString ("Textvergleich:");
		this.table3.Add (this.labelTextComp);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelTextComp]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add (this.table3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table3]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table4 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), true);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.radioAddition = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Addieren"));
		this.radioAddition.CanFocus = true;
		this.radioAddition.Name = "radioAddition";
		this.radioAddition.DrawIndicator = true;
		this.radioAddition.UseUnderline = true;
		this.radioAddition.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.table4.Add (this.radioAddition);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table4 [this.radioAddition]));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.radioDivision = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Dividieren"));
		this.radioDivision.CanFocus = true;
		this.radioDivision.Name = "radioDivision";
		this.radioDivision.DrawIndicator = true;
		this.radioDivision.UseUnderline = true;
		this.radioDivision.Group = this.radioAddition.Group;
		this.table4.Add (this.radioDivision);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table4 [this.radioDivision]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.radioMultiplication = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Multiplizieren"));
		this.radioMultiplication.CanFocus = true;
		this.radioMultiplication.Name = "radioMultiplication";
		this.radioMultiplication.DrawIndicator = true;
		this.radioMultiplication.UseUnderline = true;
		this.radioMultiplication.Group = this.radioAddition.Group;
		this.table4.Add (this.radioMultiplication);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table4 [this.radioMultiplication]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.radioSubtraction = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Subtrahieren"));
		this.radioSubtraction.CanFocus = true;
		this.radioSubtraction.Name = "radioSubtraction";
		this.radioSubtraction.DrawIndicator = true;
		this.radioSubtraction.UseUnderline = true;
		this.radioSubtraction.Group = this.radioAddition.Group;
		this.table4.Add (this.radioSubtraction);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table4 [this.radioSubtraction]));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add (this.table4);
		this.frame1.Add (this.GtkAlignment);
		this.frameOperations = new global::Gtk.Label ();
		this.frameOperations.Name = "frameOperations";
		this.frameOperations.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Operationen:</b>");
		this.frameOperations.UseMarkup = true;
		this.frame1.LabelWidget = this.frameOperations;
		this.vbox2.Add (this.frame1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.buttonOk = new global::Gtk.Button ();
		this.buttonOk.CanFocus = true;
		this.buttonOk.Name = "buttonOk";
		this.buttonOk.UseStock = true;
		this.buttonOk.UseUnderline = true;
		this.buttonOk.Label = "gtk-cancel";
		this.hbuttonbox2.Add (this.buttonOk);
		global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.buttonOk]));
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.buttonCancel = new global::Gtk.Button ();
		this.buttonCancel.CanFocus = true;
		this.buttonCancel.Name = "buttonCancel";
		this.buttonCancel.UseStock = true;
		this.buttonCancel.UseUnderline = true;
		this.buttonCancel.Label = "gtk-ok";
		this.hbuttonbox2.Add (this.buttonCancel);
		global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.buttonCancel]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox2.Add (this.hbuttonbox2);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 658;
		this.DefaultHeight = 308;
		this.Show ();
		this.buttonOk.Clicked += new global::System.EventHandler (this.CancelButtonClicked);
	}
}
